"""Repository discovery, redaction, and deterministic bundle rendering."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import re
import subprocess
from typing import Iterable


DEFAULT_IGNORED_DIRS = frozenset(
    {
        ".git",
        ".hg",
        ".svn",
        ".venv",
        "venv",
        "node_modules",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        ".tox",
        ".nox",
        "dist",
        "build",
        "coverage",
        "htmlcov",
        ".idea",
        ".vscode",
    }
)

SENSITIVE_FILENAMES = frozenset(
    {
        ".env",
        ".env.local",
        ".env.production",
        ".env.development",
        "id_rsa",
        "id_dsa",
        "id_ecdsa",
        "id_ed25519",
        "credentials",
        "credentials.json",
        "secrets.json",
    }
)

SENSITIVE_SUFFIXES = frozenset(
    {".pem", ".key", ".p12", ".pfx", ".jks", ".kdbx", ".sqlite", ".sqlite3"}
)

_PRIVATE_KEY_PATTERN = re.compile(
    r"-----BEGIN [^-]*PRIVATE KEY-----.*?-----END [^-]*PRIVATE KEY-----",
    re.DOTALL,
)
_OPENAI_KEY_PATTERN = re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b")
_GITHUB_TOKEN_PATTERN = re.compile(r"\bgh[pousr]_[A-Za-z0-9_]{20,}\b")
_AWS_KEY_PATTERN = re.compile(r"\bAKIA[0-9A-Z]{16}\b")
_BEARER_PATTERN = re.compile(r"(?i)(\bBearer\s+)[A-Za-z0-9._~+/=-]{20,}")
_ASSIGNMENT_PATTERN = re.compile(
    r"(?im)^(\s*(?:api[_-]?key|secret|token|password|passwd)\s*[:=]\s*)([\"']?)([^\"'\s#]+)"
)


@dataclass(frozen=True, slots=True)
class PackOptions:
    """Controls repository discovery and bundle size limits."""

    root: Path
    max_file_bytes: int = 120_000
    max_total_bytes: int = 1_000_000
    max_files: int = 200
    respect_gitignore: bool = True
    redact_secrets: bool = True

    def __post_init__(self) -> None:
        root = Path(self.root).expanduser().resolve()
        if not root.exists() or not root.is_dir():
            raise ValueError(f"root must be an existing directory: {root}")
        for name, value in (
            ("max_file_bytes", self.max_file_bytes),
            ("max_total_bytes", self.max_total_bytes),
            ("max_files", self.max_files),
        ):
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                raise ValueError(f"{name} must be a positive integer")
        object.__setattr__(self, "root", root)


@dataclass(frozen=True, slots=True)
class FileRecord:
    """One file included in a context bundle."""

    path: str
    size_bytes: int
    sha256: str
    content: str
    redactions: int = 0

    def as_dict(self) -> dict[str, object]:
        return {
            "path": self.path,
            "size_bytes": self.size_bytes,
            "sha256": self.sha256,
            "redactions": self.redactions,
            "content": self.content,
        }


@dataclass(frozen=True, slots=True)
class PackResult:
    """The included files and explicit reasons for skipped files."""

    root_name: str
    files: tuple[FileRecord, ...]
    skipped: tuple[dict[str, str], ...]
    source_bytes: int

    @property
    def redaction_count(self) -> int:
        return sum(record.redactions for record in self.files)

    def as_dict(self) -> dict[str, object]:
        return {
            "schema_version": 1,
            "root": self.root_name,
            "summary": {
                "included_files": len(self.files),
                "skipped_files": len(self.skipped),
                "source_bytes": self.source_bytes,
                "redactions": self.redaction_count,
            },
            "files": [record.as_dict() for record in self.files],
            "skipped": list(self.skipped),
        }

    def to_json(self) -> str:
        """Render a stable, machine-readable JSON bundle."""

        return json.dumps(self.as_dict(), ensure_ascii=False, indent=2) + "\n"

    def to_markdown(self) -> str:
        """Render a human-readable bundle safe to paste into a review tool."""

        lines = [
            f"# Context bundle: `{self.root_name}`",
            "",
            "> Generated by Context Kit. Sensitive filenames are excluded and detected secrets are redacted.",
            "",
            "## Summary",
            "",
            f"- Included files: {len(self.files)}",
            f"- Skipped files: {len(self.skipped)}",
            f"- Source bytes: {self.source_bytes}",
            f"- Redactions: {self.redaction_count}",
            "",
            "## File tree",
            "",
        ]
        lines.extend(f"- `{record.path}`" for record in self.files)
        if not self.files:
            lines.append("- _(no files included)_")

        lines.extend(["", "## File contents", ""])
        for record in self.files:
            lines.extend(
                [
                    f"### `{record.path}`",
                    "",
                    f"- SHA-256: `{record.sha256}`",
                    f"- Original size: {record.size_bytes} bytes",
                    f"- Redactions: {record.redactions}",
                    "",
                    _fenced_text(record.content),
                    "",
                ]
            )

        if self.skipped:
            lines.extend(["## Skipped files", ""])
            lines.extend(
                f"- `{item['path']}` — {item['reason']}" for item in self.skipped
            )
            lines.append("")
        return "\n".join(lines)


def _fenced_text(content: str) -> str:
    longest = max((len(match) for match in re.findall(r"`+", content)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}text\n{content.rstrip()}\n{fence}"


def _is_sensitive_name(path: Path) -> bool:
    name = path.name.lower()
    return (
        name in SENSITIVE_FILENAMES
        or name.startswith(".env.")
        or path.suffix.lower() in SENSITIVE_SUFFIXES
    )


def _candidate_paths(root: Path) -> list[Path]:
    candidates: list[Path] = []
    for path in root.rglob("*"):
        if path.is_symlink() or not path.is_file():
            continue
        relative = path.relative_to(root)
        if any(part in DEFAULT_IGNORED_DIRS for part in relative.parts):
            continue
        candidates.append(path)
    return sorted(candidates, key=lambda path: path.relative_to(root).as_posix().lower())


def _git_ignored(root: Path, paths: Iterable[Path]) -> set[str]:
    relative_names = [path.relative_to(root).as_posix() for path in paths]
    if not relative_names:
        return set()
    ignored: set[str] = set()
    # ``git check-ignore --stdin`` reports matches on stdout but its exit code
    # depends on the final input path. Checking one path at a time keeps a
    # mixed list of ignored and visible files reliable across Git versions.
    for relative in relative_names:
        try:
            result = subprocess.run(
                ["git", "check-ignore", "--no-index", "--quiet", "--", relative],
                cwd=root,
                capture_output=True,
                text=True,
                timeout=3,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            return set()
        if result.returncode == 0:
            ignored.add(relative)
        elif result.returncode != 1:
            return set()
    return ignored


def _redact_text(text: str) -> tuple[str, int]:
    count = 0
    for pattern, replacement in (
        (_PRIVATE_KEY_PATTERN, "[REDACTED PRIVATE KEY]"),
        (_OPENAI_KEY_PATTERN, "sk-[REDACTED]"),
        (_GITHUB_TOKEN_PATTERN, "gh_[REDACTED]"),
        (_AWS_KEY_PATTERN, "AKIA[REDACTED]"),
        (_BEARER_PATTERN, r"\1[REDACTED]"),
    ):
        text, replaced = pattern.subn(replacement, text)
        count += replaced

    def replace_assignment(match: re.Match[str]) -> str:
        quote = match.group(2)
        return f"{match.group(1)}{quote}[REDACTED]{quote}"

    text, replaced = _ASSIGNMENT_PATTERN.subn(replace_assignment, text)
    return text, count + replaced


def _read_text(path: Path) -> tuple[str | None, str | None]:
    try:
        raw = path.read_bytes()
    except OSError as exc:
        return None, f"could not read file: {exc}"
    if b"\x00" in raw:
        return None, "binary file"
    try:
        return raw.decode("utf-8"), None
    except UnicodeDecodeError:
        return None, "not valid UTF-8 text"


def build_pack(options: PackOptions) -> PackResult:
    """Discover, filter, redact, and bundle files under ``options.root``."""

    candidates = _candidate_paths(options.root)
    ignored = _git_ignored(options.root, candidates) if options.respect_gitignore else set()
    included: list[FileRecord] = []
    skipped: list[dict[str, str]] = []
    source_bytes = 0

    for path in candidates:
        relative = path.relative_to(options.root).as_posix()
        if _is_sensitive_name(path):
            skipped.append({"path": relative, "reason": "sensitive filename"})
            continue
        if relative in ignored:
            skipped.append({"path": relative, "reason": "matched .gitignore"})
            continue
        if len(included) >= options.max_files:
            skipped.append({"path": relative, "reason": "file-count limit"})
            continue
        try:
            size = path.stat().st_size
        except OSError as exc:
            skipped.append({"path": relative, "reason": f"could not stat file: {exc}"})
            continue
        if size > options.max_file_bytes:
            skipped.append({"path": relative, "reason": "per-file size limit"})
            continue
        if source_bytes + size > options.max_total_bytes:
            skipped.append({"path": relative, "reason": "total-size limit"})
            continue

        content, error = _read_text(path)
        if error:
            skipped.append({"path": relative, "reason": error})
            continue
        assert content is not None
        raw = content.encode("utf-8")
        digest = hashlib.sha256(raw).hexdigest()
        redactions = 0
        if options.redact_secrets:
            content, redactions = _redact_text(content)
        included.append(
            FileRecord(
                path=relative,
                size_bytes=size,
                sha256=digest,
                content=content,
                redactions=redactions,
            )
        )
        source_bytes += size

    return PackResult(
        root_name=options.root.name or options.root.as_posix(),
        files=tuple(included),
        skipped=tuple(skipped),
        source_bytes=source_bytes,
    )
